### ISSUE TITLE
Wordscore model doesn't run

### ISSUE THREAD

**Issue by dennis-hammerschmidt** [sjankin/UnitedNations#1]
I receive the following error message at l. 193 when trying to predict the wordscores model:

Error in if (lbg_sdr == 0) 0 else lbg_sdr/lbg_sdv : missing value where TRUE/FALSE needed

It appears that the refscores didn't work as they are all NAs. Any idea why this might be the case? I didn't modify anything and just tried to re-run the entire rmd file

**Comment by sjankin** [comment]
The code broke after a change in Quanteda package API. I'll update it a bit later today.

**Comment by sjankin** [comment]
I just updated the examples notebook to address changes in quanteda API. It should work fine now.
